- name: Install prerequisites 1
  become: true
  apt:
    name:
      [
        "curl",
        "zip",
        "unzip",
        "tar",
        "git",
        "ripgrep",
        "build-essential",
        "texinfo",
        "libx11-dev",
        "libxpm-dev",
        "libjpeg-dev",
        "libpng-dev",
        "libgif-dev",
        "libtiff-dev",
        "libgtk2.0-dev",
        "libncurses-dev",
        "libgnutls28-dev",
        "libjansson4",
        "libjansson-dev",
        "cmake",
        "libtool",
        "libtool-bin",
        "htop",
        "fd-find",
      ]
  tags:
    - core
    - emacs

- name: Symlink fd-find to fd
  become: true
  shell: ln -s $(which fdfind) ~/.local/bin/fd
