- name: Install prerequisites 1
  become: true
  apt:
    name:
      [
        "curl",
        "zip",
        "unzip",
        "tar",
        "git",
        "ripgrep",
        "build-essential",
        "texinfo",
        "libx11-dev",
        "libxpm-dev",
        "libjpeg-dev",
        "libpng-dev",
        "libgif-dev",
        "libtiff-dev",
        "libgtk2.0-dev",
        "libncurses-dev",
        "libgnutls28-dev",
        "libjansson4",
        "libjansson-dev",
      ]
  tags:
    - core
    - emacs

- name: Download Emacs
  get_url:
    url: http://ftp.gnu.org/gnu/emacs/emacs-27.2.tar.gz
    dest: ./emacs
    mode: "0440"
  tags:
    - emacs

- name: Unarchive Emacs
  ansible.builtin.unarchive:
    src: ./emacs
    dest: .
  tags:
    - install
    - emacs

- name: Install Emacs
  shell: cd ./emacs-27.2 && ./configure && make && make install
  tags:
    - install
    - emacs
