- name: Create ./temp-downloads if it does not exist
  ansible.builtin.file:
    path: ./temp-downloads
    state: directory
    mode: "0755"
  tags:
    - emacs

- name: Download Emacs
  get_url:
    url: http://ftp.gnu.org/gnu/emacs/emacs-27.2.tar.gz
    dest: ./temp-downloads/emacs-27.2.tar.gz
    mode: "0440"
  tags:
    - emacs

- name: Unarchive Emacs
  shell: tar xzf ./temp-downloads/emacs-27.2.tar.gz -C ./temp-downloads/
  tags:
    - emacs

- name: Install Emacs
  shell: cd ./temp-downloads/emacs-27.2 && ./configure && make && make install
  tags:
    - emacs

- name: Download Doom
  ansible.builtin.git:
    repo: "https://github.com/hlissner/doom-emacs"
    dest: ~/.emacs.d
    depth: 1
  tags:
    - emacs
    - doom

- name: Manually install Doom
  shell: chmod +x ./doom-manual-install.sh && ./doom-manual-install.sh
  tags:
    - emacs
    - doom
